version: '3.8'

services:
    alfaguaradb:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: alfaguaradatabase
        ports:
            -  "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 10s
            retries: 5
        volumes:
            - alfaguara-db-data:/var/lib/mysql

    alfaguaraapi.api:
        image: alfaguaraapi
        build:            
            context: .
            dockerfile: Dockerfile
        ports:            
            - "8080:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
        depends_on:
            alfaguaradb:
                condition: service_healthy
volumes:
    alfaguara-db-data: 
        driver: local
  